name: Frontend Deployment

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.1  # Specify the Node.js version you are using

      - name: Install Dependencies
        run: npm install --force
        working-directory: ./frontend-app  # Set the working directory to the frontend-app subdirectory

      - name: Build Frontend
        run: npm run build
        working-directory: ./frontend-app  # Set the working directory to the frontend-app subdirectory

      # You can add additional steps here for running tests, code analysis, etc.

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: frontend-gh-pages  # Specify a unique branch for the frontend deployment
          folder: ./frontend-app/build  # Set the folder containing the build output


